import json
import tempfile
import unittest
from pathlib import Path

from Tools.map_generator import RecipeError, generate_map, write_map
from Tools.map_validator import MapValidator


ROOT = Path(__file__).resolve().parents[2]
TILES_PATH = ROOT / "Mods" / "Dimensionfall" / "Tiles" / "Tiles.json"


def valid_recipe():
    return {
        "id": "generated_test_map",
        "name": "Generated Test Map",
        "description": "Generated by a unit test.",
        "seed": 12345,
        "base_tile": {"id": "grass_plain_01", "rotation": "random"},
        "regions": [],
    }


class MapGeneratorTests(unittest.TestCase):
    def test_successful_generation_has_complete_map_shape(self):
        generated = generate_map(valid_recipe(), TILES_PATH)

        self.assertEqual(generated["id"], "generated_test_map")
        self.assertEqual(generated["name"], "Generated Test Map")
        self.assertEqual(generated["description"], "Generated by a unit test.")
        self.assertEqual(generated["mapwidth"], 32)
        self.assertEqual(generated["mapheight"], 32)
        self.assertEqual(generated["categories"], [])
        self.assertEqual(generated["weight"], 1000)
        self.assertEqual(
            generated["connections"],
            {
                "north": "ground",
                "east": "ground",
                "south": "ground",
                "west": "ground",
            },
        )
        self.assertEqual(len(generated["levels"]), 21)
        self.assertTrue(all(level == [] for level in generated["levels"][:10]))
        self.assertEqual(len(generated["levels"][10]), 1024)
        self.assertTrue(all(level == [] for level in generated["levels"][11:]))

    def test_generation_is_deterministic_for_the_same_seed(self):
        first = generate_map(valid_recipe(), TILES_PATH)
        second = generate_map(valid_recipe(), TILES_PATH)

        self.assertEqual(first, second)
        self.assertEqual(
            [tile.get("rotation", 0) for tile in first["levels"][10][:12]],
            [270, 0, 180, 180, 90, 180, 270, 90, 180, 0, 270, 180],
        )

    def test_rectangular_regions_replace_tiles_in_row_major_grid(self):
        recipe = valid_recipe()
        recipe["base_tile"] = {"id": "grass_plain_01"}
        recipe["regions"] = [
            {
                "x": 1,
                "y": 1,
                "width": 2,
                "height": 2,
                "tile": {"id": "dirt_light_00", "rotation": 90},
            }
        ]

        level = generate_map(recipe, TILES_PATH)["levels"][10]

        expected_region_indexes = {33, 34, 65, 66}
        for index, tile in enumerate(level):
            if index in expected_region_indexes:
                self.assertEqual(tile, {"id": "dirt_light_00", "rotation": 90})
            else:
                self.assertEqual(tile, {"id": "grass_plain_01"})

    def test_null_region_tile_uses_the_existing_empty_dictionary_representation(self):
        recipe = valid_recipe()
        recipe["regions"] = [
            {"x": 0, "y": 0, "width": 1, "height": 1, "tile": None}
        ]

        generated = generate_map(recipe, TILES_PATH)

        self.assertEqual(generated["levels"][10][0], {})

    def test_set_operation_places_one_tile(self):
        recipe = valid_recipe()
        recipe["base_tile"] = {"id": "grass_plain_01"}
        recipe["operations"] = [
            {"type": "set", "x": 3, "y": 2, "tile": {"id": "dirt_light_00"}}
        ]

        level = generate_map(recipe, TILES_PATH)["levels"][10]

        self.assertEqual(level[2 * 32 + 3], {"id": "dirt_light_00"})
        self.assertEqual(level[2 * 32 + 2], {"id": "grass_plain_01"})

    def test_rectangle_operation_is_filled_and_later_operations_overwrite(self):
        recipe = valid_recipe()
        recipe["base_tile"] = {"id": "grass_plain_01"}
        recipe["operations"] = [
            {
                "type": "rectangle",
                "x": 1,
                "y": 1,
                "width": 3,
                "height": 2,
                "tile": {"id": "dirt_light_00"},
            },
            {"type": "set", "x": 2, "y": 1, "tile": None},
        ]

        level = generate_map(recipe, TILES_PATH)["levels"][10]

        for index in {33, 35, 65, 66, 67}:
            self.assertEqual(level[index], {"id": "dirt_light_00"})
        self.assertEqual(level[34], {})

    def test_rectangle_outline_places_only_border_and_handles_thin_rectangles(self):
        recipe = valid_recipe()
        recipe["base_tile"] = {"id": "grass_plain_01"}
        recipe["operations"] = [
            {
                "type": "rectangle_outline",
                "x": 1,
                "y": 1,
                "width": 3,
                "height": 3,
                "tile": {"id": "dirt_light_00"},
            },
            {
                "type": "rectangle_outline",
                "x": 6,
                "y": 1,
                "width": 1,
                "height": 3,
                "tile": None,
            },
        ]

        level = generate_map(recipe, TILES_PATH)["levels"][10]

        self.assertEqual(level[2 * 32 + 2], {"id": "grass_plain_01"})
        for x, y in ((1, 1), (2, 1), (3, 1), (1, 2), (3, 2), (1, 3), (2, 3), (3, 3)):
            self.assertEqual(level[y * 32 + x], {"id": "dirt_light_00"})
        for y in range(1, 4):
            self.assertEqual(level[y * 32 + 6], {})

    def test_line_operation_handles_horizontal_vertical_and_diagonal_lines(self):
        recipe = valid_recipe()
        recipe["base_tile"] = {"id": "grass_plain_01"}
        recipe["operations"] = [
            {
                "type": "line",
                "from": [1, 1],
                "to": [4, 1],
                "tile": {"id": "dirt_light_00"},
            },
            {
                "type": "line",
                "from": [6, 1],
                "to": [6, 4],
                "tile": {"id": "dirt_light_00"},
            },
            {
                "type": "line",
                "from": [8, 1],
                "to": [11, 4],
                "tile": None,
            },
        ]

        level = generate_map(recipe, TILES_PATH)["levels"][10]

        for x in range(1, 5):
            self.assertEqual(level[1 * 32 + x], {"id": "dirt_light_00"})
        for y in range(1, 5):
            self.assertEqual(level[y * 32 + 6], {"id": "dirt_light_00"})
        for x, y in ((8, 1), (9, 2), (10, 3), (11, 4)):
            self.assertEqual(level[y * 32 + x], {})

    def test_scatter_count_is_exact_deterministic_and_replaces_existing_tiles(self):
        recipe = valid_recipe()
        recipe["base_tile"] = {"id": "grass_plain_01"}
        recipe["operations"] = [
            {
                "type": "scatter",
                "region": {"x": 4, "y": 5, "width": 4, "height": 3},
                "count": 5,
                "tile": {"id": "dirt_light_00"},
            }
        ]

        first = generate_map(recipe, TILES_PATH)["levels"][10]
        second = generate_map(recipe, TILES_PATH)["levels"][10]
        scattered = {
            (index % 32, index // 32)
            for index, tile in enumerate(first)
            if tile == {"id": "dirt_light_00"}
        }

        self.assertEqual(first, second)
        self.assertEqual(len(scattered), 5)
        self.assertTrue(all(4 <= x < 8 and 5 <= y < 8 for x, y in scattered))

    def test_scatter_density_uses_floor_of_region_area(self):
        recipe = valid_recipe()
        recipe["base_tile"] = {"id": "grass_plain_01"}
        recipe["operations"] = [
            {
                "type": "scatter",
                "region": {"x": 0, "y": 0, "width": 3, "height": 3},
                "density": 0.5,
                "tile": {"id": "dirt_light_00"},
            }
        ]

        level = generate_map(recipe, TILES_PATH)["levels"][10]

        self.assertEqual(level.count({"id": "dirt_light_00"}), 4)

    def test_invalid_operations_are_rejected_with_clear_errors(self):
        base_region = {"x": 0, "y": 0, "width": 2, "height": 2}
        cases = [
            ("not-an-array", "operations must be an array"),
            ([{"type": "unknown"}], "unknown operation 'unknown'"),
            (
                [{"type": "set", "x": 32, "y": 0, "tile": None}],
                "operations\\[0\\].x must be an integer between 0 and 31",
            ),
            (
                [{"type": "set", "x": 0, "y": 0, "tile": None, "extra": 1}],
                "unknown operations\\[0\\] field 'extra'",
            ),
            (
                [
                    {
                        "type": "rectangle",
                        "x": 31,
                        "y": 0,
                        "width": 2,
                        "height": 1,
                        "tile": None,
                    }
                ],
                "extends outside the 32x32 map",
            ),
            (
                [{"type": "line", "from": [0, 0], "to": [32, 0], "tile": None}],
                "operations\\[0\\].to\\[0\\] must be an integer between 0 and 31",
            ),
            (
                [{"type": "scatter", "region": base_region, "tile": None}],
                "must define exactly one of count or density",
            ),
            (
                [
                    {
                        "type": "scatter",
                        "region": base_region,
                        "count": 1,
                        "density": 0.5,
                        "tile": None,
                    }
                ],
                "must define exactly one of count or density",
            ),
            (
                [
                    {
                        "type": "scatter",
                        "region": base_region,
                        "count": 5,
                        "tile": None,
                    }
                ],
                "count must be an integer between 0 and 4",
            ),
            (
                [
                    {
                        "type": "scatter",
                        "region": base_region,
                        "count": 0,
                        "tile": {"id": "missing_tile"},
                    }
                ],
                "unknown tile 'missing_tile'",
            ),
            (
                [
                    {
                        "type": "scatter",
                        "region": base_region,
                        "density": True,
                        "tile": None,
                    }
                ],
                "density must be a number between 0 and 1",
            ),
            (
                [
                    {
                        "type": "scatter",
                        "region": {**base_region, "extra": 1},
                        "count": 1,
                        "tile": None,
                    }
                ],
                "unknown operations\\[0\\].region field 'extra'",
            ),
        ]
        for operations, expected_message in cases:
            with self.subTest(operations=operations):
                recipe = valid_recipe()
                recipe["operations"] = operations
                with self.assertRaisesRegex(RecipeError, expected_message):
                    generate_map(recipe, TILES_PATH)

    def test_operations_require_an_explicit_tile_field(self):
        operations = [
            {"type": "set", "x": 0, "y": 0},
            {"type": "rectangle", "x": 0, "y": 0, "width": 1, "height": 1},
            {
                "type": "rectangle_outline",
                "x": 0,
                "y": 0,
                "width": 1,
                "height": 1,
            },
            {"type": "line", "from": [0, 0], "to": [1, 1]},
            {
                "type": "scatter",
                "region": {"x": 0, "y": 0, "width": 1, "height": 1},
                "count": 0,
            },
        ]
        for operation in operations:
            with self.subTest(operation=operation):
                recipe = valid_recipe()
                recipe["operations"] = [operation]
                with self.assertRaisesRegex(
                    RecipeError, "operations\\[0\\].tile is required"
                ):
                    generate_map(recipe, TILES_PATH)

    def test_invalid_recipes_are_rejected_with_clear_errors(self):
        cases = [
            (
                {"id": "../unsafe"},
                "id may contain only letters, numbers, underscores, and hyphens",
            ),
            ({"base_tile": {"id": "missing_tile"}}, "unknown tile 'missing_tile'"),
            (
                {
                    "regions": [
                        {"x": 0, "width": "two", "height": 1, "tile": None}
                    ]
                },
                "regions\\[0\\].y must be a non-negative integer",
            ),
            (
                {
                    "regions": [
                        {
                            "x": 31,
                            "y": 31,
                            "width": 2,
                            "height": 1,
                            "tile": None,
                        }
                    ]
                },
                "extends outside the 32x32 map",
            ),
            ({"unexpected": True}, "unknown recipe field 'unexpected'"),
            (
                {
                    "regions": [
                        {
                            "x": 0,
                            "y": 0,
                            "width": 1,
                            "height": 1,
                            "tile": None,
                            "unexpected": True,
                        }
                    ]
                },
                "unknown regions\\[0\\] field 'unexpected'",
            ),
            (
                {"base_tile": {"id": "grass_plain_01", "unexpected": True}},
                "unknown base_tile field 'unexpected'",
            ),
        ]
        for changes, expected_message in cases:
            with self.subTest(changes=changes):
                recipe = valid_recipe()
                recipe.update(changes)
                with self.assertRaisesRegex(ValueError, expected_message):
                    generate_map(recipe, TILES_PATH)

    def test_recipe_dimensions_are_not_configurable(self):
        for field in ("width", "height"):
            with self.subTest(field=field):
                recipe = valid_recipe()
                recipe[field] = 32
                with self.assertRaisesRegex(
                    RecipeError, f"unknown recipe field '{field}'"
                ):
                    generate_map(recipe, TILES_PATH)

    def test_example_recipe_generates_successfully(self):
        recipe_path = ROOT / "Tools" / "examples" / "map_recipe.json"
        generated = generate_map(
            json.loads(recipe_path.read_text(encoding="utf-8")), TILES_PATH
        )

        self.assertEqual(generated["mapwidth"], 32)
        self.assertEqual(generated["mapheight"], 32)
        self.assertEqual(len(generated["levels"][10]), 1024)

    def test_invalid_unicode_metadata_is_rejected_with_a_clear_error(self):
        with tempfile.TemporaryDirectory() as directory:
            directory_path = Path(directory)
            recipe = valid_recipe()
            recipe["name"] = "\ud800"
            recipe_path = directory_path / "recipe.json"
            recipe_path.write_text(json.dumps(recipe), encoding="utf-8")

            with self.assertRaisesRegex(ValueError, "name must contain valid Unicode"):
                write_map(
                    recipe_path,
                    directory_path / "generated_test_map.json",
                    TILES_PATH,
                )

    def test_malformed_tile_database_is_rejected_with_a_clear_error(self):
        with tempfile.TemporaryDirectory() as directory:
            tiles_path = Path(directory) / "Tiles.json"
            tiles_path.write_text("42", encoding="utf-8")

            with self.assertRaisesRegex(ValueError, "tile database must be a JSON array"):
                generate_map(valid_recipe(), tiles_path)

    def test_output_filename_must_match_map_id(self):
        with tempfile.TemporaryDirectory() as directory:
            recipe_path = Path(directory) / "recipe.json"
            recipe_path.write_text(json.dumps(valid_recipe()), encoding="utf-8")

            with self.assertRaisesRegex(ValueError, "must be named generated_test_map.json"):
                write_map(recipe_path, Path(directory) / "different.json", TILES_PATH)

    def test_write_map_protects_existing_output_unless_overwrite_is_enabled(self):
        with tempfile.TemporaryDirectory() as directory:
            directory_path = Path(directory)
            recipe_path = directory_path / "recipe.json"
            output_path = directory_path / "generated_test_map.json"
            recipe_path.write_text(json.dumps(valid_recipe()), encoding="utf-8")
            output_path.write_text("original", encoding="utf-8")

            with self.assertRaisesRegex(FileExistsError, "use --overwrite"):
                write_map(recipe_path, output_path, TILES_PATH)
            self.assertEqual(output_path.read_text(encoding="utf-8"), "original")

            write_map(recipe_path, output_path, TILES_PATH, overwrite=True)
            self.assertEqual(
                json.loads(output_path.read_text(encoding="utf-8"))["id"],
                "generated_test_map",
            )


class MapValidatorDimensionTests(unittest.TestCase):
    def validate(self, map_data):
        with tempfile.TemporaryDirectory() as directory:
            map_path = Path(directory) / "test_map.json"
            map_path.write_text(json.dumps(map_data), encoding="utf-8")
            validator = MapValidator()
            validator.validate_map(str(map_path))
            return validator.errors

    def test_rejects_nonstandard_map_width(self):
        map_data = generate_map(valid_recipe(), TILES_PATH)
        map_data["mapwidth"] = 31

        errors = self.validate(map_data)

        self.assertTrue(any("mapwidth" in error for error in errors))
        self.assertTrue(any("expected 32, actual 31" in error for error in errors))
        self.assertTrue(all("test_map.json" in error for error in errors))

    def test_rejects_nonstandard_map_height(self):
        map_data = generate_map(valid_recipe(), TILES_PATH)
        map_data["mapheight"] = 33

        errors = self.validate(map_data)

        self.assertTrue(any("mapheight" in error for error in errors))
        self.assertTrue(any("expected 32, actual 33" in error for error in errors))

    def test_rejects_populated_level_with_too_few_tiles(self):
        map_data = generate_map(valid_recipe(), TILES_PATH)
        map_data["levels"][10].pop()

        errors = self.validate(map_data)

        self.assertTrue(any("Level 10" in error for error in errors))
        self.assertTrue(any("expected 1024, actual 1023" in error for error in errors))

    def test_rejects_populated_level_with_too_many_tiles(self):
        map_data = generate_map(valid_recipe(), TILES_PATH)
        map_data["levels"][10].append({})

        errors = self.validate(map_data)

        self.assertTrue(any("Level 10" in error for error in errors))
        self.assertTrue(any("expected 1024, actual 1025" in error for error in errors))

    def test_accepts_empty_unused_levels(self):
        map_data = generate_map(valid_recipe(), TILES_PATH)

        self.assertEqual(map_data["levels"][0], [])
        self.assertEqual(self.validate(map_data), [])


if __name__ == "__main__":
    unittest.main()
